There was a problem uploading the ZIP file "{{ zip.blob_name }}", in the Cohort "{{ zip.cohort.name }}".

{% if original_blob_name_preexisting %}
The following file names within the ZIP file already exist within the Cohort:
{% for original_blob_name in original_blob_name_preexisting %}
  * "{{ original_blob_name }}"
{% endfor %}
{% endif %}

{% if original_blob_name_duplicates %}
The following file names are duplicated within the ZIP file:
{% for original_blob_name in original_blob_name_duplicates %}
  * "{{ original_blob_name }}"
{% endfor %}
{% endif %}
